server:
  port: 8090


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
           - path=/user/**

        - id: item-service
          uri: lb://item-service
          predicates:
           - path=/item/**



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defuaultZone: http://localhost:8761/eureka
